In [2]:
def convert(conversion_type, value):
    conversions = {
        '1': value * 3.28084,
        '2': value / 3.28084,
        '3': value * 2.20462,
        '4': value / 2.20462,
        '5': value * 0.264172,
        '6': value / 0.264172
    }
    return conversions[conversion_type]


print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = input("Enter choice (1-6): ")
    if choice not in ['1','2','3','4','5','6']:
        raise ValueError("Invalid choice")
    value = float(input("Enter value: "))
    result = convert(choice, value)
    print(f"Result: {result:.4f}")

except ValueError as e:
    print(f"Error: {e}")

1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Result: 20.1168


In [10]:
def get_sum(numbers):
    return sum(numbers)

def get_average(numbers):
    return sum(numbers) / len(numbers)

def get_maximum(numbers):
    return max(numbers)

def get_minimum(numbers):
    return min(numbers)


print("1. Sum")
print("2. Average")
print("3. Maximum")
print("4. Minimum")

try:
    choice = input("Enter choice (1-4): ")
    if choice not in ['1','2','3','4']:
        raise ValueError("Invalid choice")

    numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

    if len(numbers) == 0:
        raise ValueError("List is empty")

    operations = {
        '1': get_sum,
        '2': get_average,
        '3': get_maximum,
        '4': get_minimum
    }

    result = operations[choice](numbers)
    print(f"Result: {result}")

except ValueError as e:
    print(f"Error: {e}")

1. Sum
2. Average
3. Maximum
4. Minimum
Result: 6.0


In [12]:
def extract_every_other(lst):
    return lst[::2]


def get_sublist(lst, start, end):
    return lst[start:end+1]


def reverse_list(lst):
    return lst[::-1]


def remove_first_last(lst):
    return lst[1:-1]


def get_first_n(lst, n):
    return lst[:n]


def get_last_n(lst, n):
    return lst[-n:]


def reverse_skip(lst):
    return lst[-2::-2]


print(extract_every_other([1, 2, 3, 4, 5, 6]))
print(get_sublist([1, 2, 3, 4, 5, 6], 2, 4))
print(reverse_list([1, 2, 3, 4, 5]))
print(remove_first_last([1, 2, 3, 4, 5]))
print(get_first_n([1, 2, 3, 4, 5], 3))
print(get_last_n([1, 2, 3, 4, 5], 2))
print(reverse_skip([1, 2, 3, 4, 5, 6]))


[1, 3, 5]
[3, 4, 5]
[5, 4, 3, 2, 1]
[2, 3, 4]
[1, 2, 3]
[4, 5]
[5, 3, 1]


In [15]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result


def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst


def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result


def find_max(lst):
    flat = flatten(lst)
    return max(flat)


def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result


def average_nested(lst):
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)


print(flatten([[1, 2], [3, 4], [5]]))
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print(sum_nested([[1, 2], [3, [4, 5]], 6]))
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))
print(find_max([[1, 2], [3, [4, 5]], 6]))
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(average_nested([[1, 2], [3, 4], [5, 6]]))


[1, 2, 3, 4, 5]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


In [3]:
# Problem 1
import numpy as np


arr1 = np.empty((2,2))
print(f"arrary1:\n {arr1}\n")

arr2 = np.ones((4,2))
print(f"arr2: \n {arr2}\n")

arr3 = np.full((3,3), 4)
print(f"arr3: \n {arr3}\n")

arr4 = np.full_like(arr3, 45)
print(f"arr4: \n {arr4}\n")

arr5 = np.full_like(arr2, 66)
print(f"arr5: \n {arr5}\n")

new_list = [1,2,3,4]
print(f" arr6:\n{np.array(new_list)}\n")


arrary1:
 [[1.06481653e+248 1.39621834e+195]
 [4.09823863e+093 9.73469813e-309]]

arr2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

arr3: 
 [[4 4 4]
 [4 4 4]
 [4 4 4]]

arr4: 
 [[45 45 45]
 [45 45 45]
 [45 45 45]]

arr5: 
 [[66. 66.]
 [66. 66.]
 [66. 66.]
 [66. 66.]]

 arr6:
[1 2 3 4]



In [4]:
arr = np.arange(10, 50)
print(arr)

arr = np.arange(9).reshape(3,3)
print(arr)

arr = np.eye(3)
print(arr)

arr = np.random.random(30)

mean_value = arr.mean()

print(arr)
print("Mean:", mean_value)

arr = np.random.random((10,10))

print(arr)

print("Minimum:", arr.min())
print("Maximum:", arr.max())

arr = np.zeros(10)

arr[4] = 1

print(arr)

arr = np.array([1,2,0,0,4,0])

reversed_arr = arr[::-1]

print("reversed adsadsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaray",reversed_arr)


arr = np.ones((5,5))

arr[1:-1, 1:-1] = 0

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.71442243 0.64235313 0.48968452 0.90712171 0.85243214 0.61010913
 0.19784313 0.06755456 0.63068081 0.44257846 0.17266117 0.18889662
 0.93193587 0.88702718 0.83297887 0.39299908 0.91820653 0.77813815
 0.21501813 0.59970299 0.40418675 0.62987558 0.75231531 0.36898396
 0.89428599 0.08630825 0.19494569 0.81184264 0.69355935 0.58985933]
Mean: 0.5632835828626639
[[0.1747587  0.78190888 0.71878554 0.95672229 0.91564737 0.68118414
  0.20049058 0.23367028 0.4091546  0.52082898]
 [0.31756881 0.30008027 0.13654254 0.14998393 0.68931847 0.97298511
  0.41748318 0.4752796  0.68172082 0.18905169]
 [0.03304357 0.59227646 0.19801377 0.05275614 0.22648668 0.8909636
  0.15447807 0.42393182 0.92481646 0.03841232]
 [0.84396391 0.42459511 0.11770459 0.48432488 0.08981792 0.4549365
  0.87557733 0.31660616 0.10502647 0.204

In [5]:
#problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x + y)
print(x - y)
print(x * 3)
print(x ** 2)
print(np.dot(v,w))
print(np.dot(x,v))
print(np.dot(x,y))

print(np.concatenate((x,y), axis=0))
print(np.concatenate((v,w), axis=0))

try:
    np.concatenate((x,v))
except Exception as e:
    print(f"Error occured: {e} because concatioation of matrix is only possible of their dimensions are same")


[[ 6  8]
 [10 13]]
[[-4 -4]
 [-4 -3]]
[[ 3  6]
 [ 9 15]]
[[ 1  4]
 [ 9 25]]
219
[29 77]
[[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[ 9 10 11 12]
Error occured: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s) because concatioation of matrix is only possible of their dimensions are same


In [6]:
# Problem 3

A = np.array([[3,4],
              [7,8]])

B = np.array([[5,3],
              [2,1]])

A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("A * A_inv:\n", np.round(result, 5))

A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]
A * A_inv:
 [[1. 0.]
 [0. 1.]]


In [7]:
AB = np.dot(A,B)
BA = np.dot(B,A)

print("AB:\n", AB)
print("BA:\n", BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [8]:
left = np.transpose(AB)

right = np.dot(B.T, A.T)

print("(AB)^T:\n", left)
print("B^T A^T:\n", right)

(AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]


In [9]:
A = np.array([
    [2,-3,1],
    [1,-1,2],
    [3,1,-1]
])
B = np.array([-1,-3,9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution:", X)

Solution: [ 2.  1. -2.]
